
security:
    access_control:
        - { path: ^/api/companies,      roles: [ROLE_ACCOUNT_MANAGER, ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/contacts,      roles: [ROLE_ACCOUNT_USER, FREE_ACCOUNT, ROLE_ACCOUNT_MANAGER], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/contactgroups,      roles: [ROLE_ACCOUNT_USER, FREE_ACCOUNT, ROLE_ACCOUNT_MANAGER], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/contentblocks,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/countries,      roles: [ROLE_ACCOUNT_MANAGER, ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/emails,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/emailcampaigns,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/emailtemplates,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/fonts,      roles: [ROLE_ACCOUNT_MANAGER, ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/languages,      roles: [ROLE_ACCOUNT_MANAGER, ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/layouts,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/logs,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/newsrooms,      roles: [ROLE_ACCOUNT_MANAGER], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/newsroomtemplates,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/users,      roles: [ROLE_ACCOUNT_MANAGER, ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/payments,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_ACCOUNT_MANAGER], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/pressreleases,      roles: [ROLE_ACCOUNT_USER, FREE_ACCOUNT, ROLE_ACCOUNT_MANAGER], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/products,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_ACCOUNT_MANAGER], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/sessions,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/settings,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/templates,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/trackemails,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/trackpressreleases,      roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN], methods: [GET, POST, PUT, PATCH, DELETE] }
